# Generated by Django 3.2.9 on 2022-01-06 06:07

from django.db import migrations, models
import django.db.models.deletion
import uuid
import website.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=200, unique=True, verbose_name="URL (auto generated. Don't touch)")),
                ('createdTime', models.DateTimeField(auto_now_add=True)),
                ('updatedTime', models.DateTimeField(auto_now=True)),
                ('date', models.DateTimeField(verbose_name='Date of Event')),
                ('title', models.CharField(max_length=100, null=True, verbose_name='Title')),
                ('content', models.TextField(null=True, verbose_name='Content')),
                ('registrationLink', models.CharField(blank=True, max_length=200, null=True, verbose_name='Registration Link')),
            ],
        ),
        migrations.CreateModel(
            name='PreviousEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=200, unique=True, verbose_name="URL (auto generated. Don't touch)")),
                ('createdTime', models.DateTimeField(auto_now_add=True)),
                ('updatedTime', models.DateTimeField(auto_now=True)),
                ('date', models.DateTimeField(verbose_name='Date of Event')),
                ('title', models.CharField(max_length=100, null=True, verbose_name='Title')),
                ('content', models.TextField(null=True, verbose_name='Content')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to=website.models.path_and_rename, verbose_name='image')),
                ('event', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='website.event')),
            ],
        ),
    ]
