# Generated by Django 3.2.9 on 2022-01-06 06:13

from django.db import migrations, models
import django.db.models.deletion
import uuid
import website.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreviousEventImages',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to=website.models.path_and_rename_previous, verbose_name='image')),
                ('previousEvent', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='website.previousevent')),
            ],
        ),
    ]
