# Generated by Django 3.2.9 on 2021-11-21 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='registrationLink',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
